In [1]:
import numpy as np

In [2]:
# 1) How many negative numbers are there?
# answer: 4

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

for i in range(len(a)):
    if (a[i] < 0):
        print(a[i], end = "  ")

-2  -1  -6  -7  

In [3]:
# 2) How many positive numbers are there?
# Answer: 5

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

for i in range(len(a)):
    if (a[i] > 0):
        print(a[i], end = "  ")

4  10  12  23  3  

In [4]:
# 3) How many even positive numbers are there?
# Answer: 6

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

print(a[(a>0) & (a % 2 == 0)])

[ 4 10 12]


In [5]:
# 4) If you were to add 3 to each data point, 
#   how many positive numbers would there be?

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

a1 = a + 3
a1[a1 > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [6]:
# 5) If you squared each number, 
# what would the new mean 
# and standard deviation be?

a2 = a**2
print("Squard: ")
print(a2)

new_mean_of_a2 = a2.mean()
print("Mean:") 
print(new_mean_of_a2)

std_of_a2 = a2.std()
print("STD:")  
print(std_of_a2)



Squard: 
[ 16 100 144 529   4   1   0   0   0  36   9  49]
Mean:
74.0
STD:
144.0243035046516


In [7]:
# 6) A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

mean_of_a = a.mean()
print(f"The mean of array 'a' is: {mean_of_a}\n")
 
centered_a = a - mean_of_a
print(f"Array 'a' after being centered: {centered_a}")





The mean of array 'a' is: 3.0

Array 'a' after being centered: [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [8]:
# 7) Calculate the z-score for each data point. 
# Recall that the z-score is given by:


 # Calculate the mean of array a: 

mean_of_a = a.mean()
print(f"The mean of array a is: {mean_of_a}\n")

# Calculate the standard deviation of array a:

std_of_a = a.std()
print(f"The standard deviation of array a is: {std_of_a}\n")

# Calculate z-score:

z_score_of_a = (a - mean_of_a)/std_of_a
z_score_of_a = np.round(z_score_of_a, decimals = 2)
print(f"The z score for each data point in array 'a' is:\n{z_score_of_a}")

The mean of array a is: 3.0

The standard deviation of array a is: 8.06225774829855

The z score for each data point in array 'a' is:
[ 0.12  0.87  1.12  2.48 -0.62 -0.5  -0.37 -0.37 -0.37 -1.12  0.   -1.24]


In [9]:

# Life w/o numpy to life with numpy

## Setup 1
aa = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_aa = sum(aa)

print(sum_of_aa)

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_aa = min(aa)

print(min_of_aa)

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_aa = max(aa)

print(max_of_aa)

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_aa = sum(aa)/len(aa)

print(mean_of_aa)

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_aa = 1

for i in aa:
    product_of_aa = product_of_aa*i

print(product_of_aa)


# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

square_of_aa = [n**2 for n in aa]
square_of_aa

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_aa = [n for n in aa if n%2 == 1]
print(odds_in_aa)


# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_aa = [n for n in aa if n%2 == 0]
print(evens_in_aa)
 




55
1
10
5.5
3628800
[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10]


In [10]:
## What about life in two dimensions? A list of lists is matrix, 
# a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, 
# max, average, sum, product, and list of squares for this 
# list of two lists.
import numpy as np

b = np.array([ [3, 4, 5], [6, 7, 8]])

b.sum()

33

In [11]:
b.min()

3

In [12]:
b.max()

8

In [13]:
b.mean()

5.5

In [14]:
b.std()

1.707825127659933

In [15]:
print('Evens:')
b[b % 2==0]

Evens:


array([4, 6, 8])

In [16]:
print('odds: ')
b[b%2==1]


odds: 


array([3, 5, 7])

In [17]:
b1 = b**2
print("Squard: ")
print(b1)


Squard: 
[[ 9 16 25]
 [36 49 64]]


In [18]:
# Exercise 1 - refactor the following to use numpy. 
# Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable 
# is a numpy array**

sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
np.array(b)

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

np.min(b)

3

In [20]:
# Exercise 3 - refactor the following maximum calculation 
# to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

np.max(b)

8

In [21]:
# Exercise 4 - refactor the following using numpy to find 
# the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

np.mean(b)


5.5

In [22]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
np.prod(b)

20160

In [23]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [24]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
b[b%2==1]

array([3, 5, 7])

In [25]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
b[b%2==0]

array([4, 6, 8])

In [26]:
# Exercise 9 - print out the shape of the array b.

print(b.shape)


(2, 3)


In [27]:
# Exercise 10 - transpose the array b.

np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [28]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

np.reshape(b,(1,6))


array([[3, 4, 5, 6, 7, 8]])

In [29]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [30]:
## Setup 3
c = [ [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
# HINT, you'll first need to make sure that the "c" variable 
# is a numpy array prior to using numpy array methods.


In [32]:
print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [33]:
# Exercise 1 - Find the min, max, sum, and product of c.

print([np.min(c), np.max(c), np.sum(c), np.prod(c)])


[1, 9, 45, 362880]


In [34]:
# Exercise 2 - Determine the standard deviation of c.

np.std(c)

2.581988897471611

In [35]:
# Exercise 3 - Determine the variance of c.

np.var(c)

6.666666666666667

In [36]:
# Exercise 4 - Print out the shape of the array c

np.shape(c)


(3, 3)

In [37]:
# Exercise 5 - Transpose c and print out transposed result.

np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [39]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

np.sum([(c) * np.transpose(c)])

261

In [40]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

np.prod([c * np.transpose(c)])

131681894400

In [41]:
## Setup 4
d = [[90, 30, 45, 0, 120, 180],[45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]]






# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2

In [42]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [43]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [44]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [49]:
# Exercise 4 - Find all the negative numbers in d

d([d < 0])

TypeError: '<' not supported between instances of 'list' and 'int'